<?php
/*
 * Created on Apr 12, 2005
 *
 * Created by Teemu Lahtela
 * (c) Lämmi
 */
 function get() {
    return array(
    
'aika'=>'Aika',
'aikalisaa' => 'Aikalis&auml; A',
'aikalisab' => 'Aikalis&auml; B',
'aloituspvm' => 'Aloittanut kauden',
'alusta' => 'Pelialusta <br>(parketti, matto, ...)',
'Ei tiedossa' => 'Ei tiedossa',
'eikaudenjoukkueesta' => 'Kaudenjoukkeesta ei ole tallennettu tietoa.',
'eitiedossa' => 'Ei tiedossa',
'eivoidamuokata' => 'Peli&auml; ei voi muokata, koska siihen on liitetty tilastomerkintöj&auml;. Tee korjaukset pelintuloksen lis&auml;ksen kautta.',
'eivoidapoistaa' => 'Peli&auml; ei voi poistaa, koska siihen on liitetty tilastomerkintöj&auml;. Tee korjaukset pelintuloksen lis&auml;ksen kautta.',
'email' => 'Email',
'etunimi' => 'Etunimi',
'f' => 'Ei',
'faxi' => 'Fax numero',
'h' => 'H',
'hallinlisays'=>'Hallin tiedot',
'hallit'=>'Hallit',
'harjoitus'=>'Harjoitus',
'henkilonlisays' => 'Henkil&ouml;n tiedot',
'henkilot'=> 'Henkil&ouml;t',
'jarjestaja' => 'J&auml;rjest&auml;j&auml;',
'joukkue' => 'Joukkue',
'joukkueenalueoikeudet'  => 'Joukkueen oikeudet',
'joukkueenlisays' => 'Joukkueen tiedot',
'joukkueet' => 'Joukkueet',
'joukkuekortti' =>'Joukkuekortti',
'joukkuetilastot' => 'Joukkueen tilastot',
'j&auml;tt&ouml;' => 'J&auml;tt&ouml;p&auml;iv&auml;',
'jaahyt' => 'J&auml;&auml;hyt',
'kaikki' => 'N&auml;yt&auml; kaikki uutiset',
'kaikkipelit' => 'Kaikki pelit',
'katisyys' => 'Katisyys',
'katuosoite' => 'Katuosoite',
'kaudenjoukkue' => 'Kauden joukkueen tiedot',
'kaudenjoukkueet' => 'Joukkueen kausien tiedot',
'kaudenlisays' => 'Uusi kausi',
'kausi' => 'Kausi',
'kayttaja' =>'K&auml;ytt&auml;j&auml;tunnus',
'kayttajanlisays' => 'K&auml;ytt&auml;j&auml;n tiedot',
'kayttajat' =>'K&auml;ytt&auml;j&auml;t',
'kayttajatunnus'=>'K&auml;ytt&auml;j&auml;tunnus',
'kenttienlkm' => 'Kenttien lukum&auml;&auml;r&auml;',
'kokoonpano' => 'Kokoonpano',
'kotihalli' => 'Kotihalli',
'kotijoukkue' => 'Kotijoukkue',
'kotipaikka' => 'Kotipaikka',
'kuva'  => 'Kuva',
'kuvaus' => 'Kuvaus',
'legendsarjatilastot' => '* V = Voitot, TP = Tasapelit, H = H&auml;vi&ouml;t, TM = Tehdyt maalit, PM = P&auml;&auml;stetyt maalit, ME = Maalien erotus, P = Pisteet',
'lempinimi' => 'Lempinimi',
'lisaa' => 'Lis&auml;&auml;',
'lisaajoukkueita'=>'Joukkueiden lis&auml;ys',
'lisaakausi'=>'Uusi kausi',
'lisaamuokkaaoikeudet' => 'Lis&auml;&auml;/muokkaa oikeudet',
'lisaasarjatyyppi'=>'Uusi sarjatyyppi',
'lisatieto' => 'Lis&auml;tieto',
'login' => 'Kirjaudu sis&auml;&auml;n',
'logo' => 'Logo',
'logout' =>'Uloskirjautuminen',
'lopetuspvm' => 'Lopetti kauden',
'lyhytnimi' => 'Lyhyt nimi',
'maa' => 'Maa',
'maalit' => 'Maalit',
'maalivahti' => 'Maalivahti',
'maila' => 'Maila',
'maskotti' => 'Maskotti',
'me' => 'ME', 
'menneetpelit' => 'Pelatut pelit',
'mpero' => 'Maalia/Ottelu',
'muokkaa' => 'Muokkaa',
'nimi' => 'Nimi',
'no' => '',
'nro' => 'Numero',
'omattiedot'=>'Omat tiedot',
'omattiedotoikeudet' => 'Tavallinen k&auml;ytt&auml;j&auml;',
'otsikko' => 'Otsikko',
'ottelut' => 'Ottelut',
'p' => 'P',
'paikka'=>'Paikka',
'paino' => 'Paino',
'paiva' => 'P&auml;iv&auml;',
'pelaajakortti' => 'Pelaajakortti',
'pelaajatilastot' => 'Pelaajien tilastot',
'peli' => 'Peli',
'peliaika' => 'Peliaika',
'pelinlisays' => 'Pelin tiedot',
'pelit' => 'Pelit',
'pelitilastot' => 'P&ouml;yt&auml;kirja',
'perustamispvm' => 'Perustamis pvm',
'pitkanimi' => 'Pitk&auml; nimi',
'pituus' => 'Pituus',
'pist' => 'Pisteet',
'plusmiinus' => '+/-',
'pm' => 'PM',
'postinumero' => 'Postinumero',
'postitoimipaikka' => 'Postitoimipaikka',
'pp' => 'Pisteet/Peli',
'puhelinnumero' => 'Puhelinnumero',
'rekisteri'=>'Rekisteriseloste',
'salasana' => 'Salasana',
'salasana2' => 'Salasana uudelleen',
'salasananvaihto' => 'Salasanan vaihto',
'sarja' => 'Sarja',
'sarjanjoukkueet'=>'Sarjojen hallinta',
'sarjanlisays' => 'Sarjan tiedot',
'sarjannimi' => 'Sarjan nimi',
'sarjanpelit' => 'Sarjan tulosten lis&auml;ys',
'sarjat' => 'Sarjat',
'sarjatilastot' => 'Sarjan tilanne',    
'sarjatyypinlisays' => 'Uusi sarjatyyppi',
'selite' => 'Selite',
'seuraid' => 'Seura',    
'seuranlisays' => 'Seuran tiedot',
'seurat' => 'Seurat',
'sukunimi' => 'Sukunimi',
'syntymaaika' => 'Syntymaaika',
'syotot' => 'Sy&ouml;t&ouml;t',
't' => 'Kyll&auml;',
'tapahtumanlisays' => 'Tapahtuman tiedot',
'tapahtumat' => 'Kaikki tapahtumat',
'tm' => 'TM',
'toimitsija1' => 'Toimitsija 1',
'toimitsija2' => 'Toimitsija 2',
'toimitsija3' => 'Toimitsija 3',
'tp' => 'TP',
'tulevatpelit' => 'Tulevat pelit',
'tulevia tapahtumia' => 'Tapahtumia',
'tuloksenlisays' => 'Tuloksen lis&auml;ys',
'tunnus' => 'Tunnus',
'tuomari1' => 'Tuomari 1',
'tuomari2' => 'Tuomari 2',
'tyypinlisays' =>'Uusi tyyppi',
'tyyppi' => 'Tyyppi',
'uusihalli' => 'Uusi halli',
'uusiseura'=>'Uusi seura',
'uusityyppi' => 'Uusi tyyppi',
'uutinen' => 'Uutinen',
'uutiset' => 'Uutiset',
'uutisia' => 'Uutisia',
'uutislista' => 'Kaikki uutiset',
'vanhasalasana' => 'Vanha salasana',
'vastuuhlo' => 'Vastuuhenkil&ouml;',
'vierasjoukkue' => 'Vierasjoukkue',
'voitot' => 'Voitot',
'yleisomaara' => 'Yleis&ouml;m&auml;&auml;r&auml;',
'yllapitooikeudet' => 'Yll&auml;pit&auml;j&auml;',
'v' => 'V'

    );
 }
function help(){
    $pakolliset = '* merkityt kent&auml;t ovat pakollisia.';
    return array(
        'joukkueenlisays'=>'Joukkue kuuluu seuraan, voit luoda uuden seuran tai luoda yhdelle seuralle' .
                ' useita joukkueita.<br> '.$pakolliset,

         'joukkueet' => 'Joukkueen nimest&auml; p&auml;&auml;set selaamaan joukkueen tietoja, kuten ' .
                'kauden kokoonpanoa. <br>' .
                'Seuran nimest&auml; p&auml;&auml;set selaamaan seuran tietoja.' ,

           'login' => 'Vasemmalla olevasta valikosta l&ouml;yd&auml;t kaiken tarvitsemasi.<br />' .
                'Etusivulta l&ouml;ytyy ilmoittautumiset tuleviin reenehin/peleihin. Omia tietoja' .
                ' p&auml;&auml;set muokkaamaan oikeasta alalaidasta.',
           'pelit' => 'P&auml;&auml;set p&ouml;yt&auml;kirjaan klikkaamaalla pelin tulosta.',
           'menneetpelit' => 'P&auml;&auml;set p&ouml;yt&auml;kirjaan klikkaamaalla pelin tulosta.',
           'seurat' => 'Seuran nimest&auml; p&auml;&auml;set seuran tietoihin.',
           'seuranlisays' => $pakolliset,
           'sarjanlisays' => $pakolliset,
           'sarjanjoukkueet' => 'Jos et saa lis&auml;ttyä joukkuetta sarjaan. Tarkista onko sille luotu kaudenjoukkue!',
           'kaudenjoukkueet' => 'Joukkueella t&auml;ytyy olla luotuna kaudelle joukkue, ' .
                'johon voi lis&auml;t&auml; pelaajia sek&auml; toimihenkil&ouml;it&auml;.',
            'hallinlisays' => $pakolliset,
            'pelinlisays' => $pakolliset,
            'henkilonlisays' => $pakolliset,
            'uutiset' => $pakolliset,
            'kayttajanlisays' => $pakolliset,
            'tapahtumanlisays' => 'Lis&auml;&auml; peli pelin lis&auml;yksen kautta!<br /><br />'.$pakolliset,
            'sarjatyypinlisays' => $pakolliset,
            'tyypinlisays' => $pakolliset,


'tuloksenlisays' => 'Tuloksen lis&auml;ys tapahtuu nelj&auml;ss&auml; vaiheessa.<BR />1. Pelin lopputuloksen sek&auml; tapahtumien m&auml;&auml;r&auml;t'.
'<br />2. Kokoonpanon valitseminen sek&auml; mahdollisesti +/-, peliajan ja lis&auml;tiedon sy&ouml;tt&ouml;'.
'<br />3. Maalien ja j&auml;&auml;hyjen merkint&auml;.'.
'<br />4. Tietojen varmistus ennen tallennusta.',

'salasananvaihto' => 'Anna nykyinen salasanasi, sek&auml; uusi kahteen kertaan.',
    );
}


?>
